name: wails-test # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Wails demo app using Svelte frontend. # 79 char long summary
description: |
  A test of packaging a Wails app for Linux.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  wails-test:
    extensions:
      - gnome-3-38
    command: bin/wails-test

parts:
  wails-test:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - node/16/stable
    override-build: |
      go get -u github.com/wailsapp/wails/cmd/wails
      $SNAPCRAFT_PART_INSTALL/bin/wails build
    organize:
      $SNAPCRAFT_PART_BUILD/build/wails-test: bin/wails-test
    prime:
      - -bin/wails