name: wails-test # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Wails demo app using Svelte frontend. # 79 char long summary
description: |
  A test of packaging a Wails app for Linux.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  wails-test:
    extensions:
      # Sets up both build and run time dependencies.
      - gnome-3-38
    command: bin/wails-test

parts:
  wails-test:
    # Using go plugin as base, but override its build commands later.
    plugin: go
    # We're using the local source tree.
    # At build time snapcraft uses the project root as working dir.
    source: .
    build-snaps:
      # Wails needs node/npm for UI build phase.
      - node/16/stable
    override-build: |
      # Install wails CLI tool.
      go get -u github.com/wailsapp/wails/cmd/wails
      # Use wails CLI tool to build project.
      $SNAPCRAFT_PART_INSTALL/bin/wails build
    organize:
      # Stage resulting binary into correct place.
      $SNAPCRAFT_PART_BUILD/build/wails-test: bin/wails-test
    prime:
      # Remove the wails CLI tool from the final snap.
      - -bin/wails